# Generated by Django 4.2.23 on 2025-08-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(null=True, upload_to='profile_photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('self_description', models.TextField(blank=True, null=True)),
                ('private_profile', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sends_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('username_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends_requests_sent', to='melaoapp.student')),
                ('username_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends_requests_received', to='melaoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='posts/')),
                ('privacy_settings', models.IntegerField()),
                ('post_date', models.DateField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sending_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField()),
                ('receiver_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='melaoapp.student')),
                ('sender_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='melaoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_like', models.DateField(blank=True, null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaoapp.post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Is_friend_of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to='melaoapp.student')),
                ('username_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to='melaoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Has',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaoapp.chat')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaoapp.post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melaoapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Belongs_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_belongs', to='melaoapp.comment')),
                ('parent_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_belongs', to='melaoapp.comment')),
            ],
        ),
    ]
