# Generated by Django 4.2.23 on 2025-08-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melaoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='favorite_book',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_color',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_music',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_videogame',
        ),
        migrations.RemoveField(
            model_name='student',
            name='known_programming_languages',
        ),
    ]
