# Generated by Django 5.2.4 on 2025-08-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melaoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
