# Generated by Django 5.2.4 on 2025-08-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melaoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
