# Generated by Django 4.2.23 on 2025-08-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melaoapp', '0002_remove_student_favorite_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='username',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='melaoapp.student'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='melaoapp.student'),
        ),
    ]
