# Generated by Django 4.2.23 on 2025-08-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melaoapp', '0002_remove_student_favorite_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
