# Generated by Django 4.2.23 on 2025-08-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melaoapp', '0003_remove_notification_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(),
        ),
    ]
