# Generated by Django 4.2.23 on 2025-08-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melaoapp', '0003_remove_notification_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='private_profile',
            field=models.BooleanField(default=False),
        ),
    ]
